# Generated by Django 4.2.7 on 2023-12-12 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dcliente',
            fields=[
                ('cli_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('cli_razaosocial', models.CharField(max_length=50)),
                ('cli_nomefantasia', models.CharField(max_length=50)),
                ('cli_cnpj', models.CharField(max_length=20)),
                ('cli_im', models.CharField(max_length=20)),
                ('cli_ie', models.CharField(max_length=20)),
                ('cli_email1', models.EmailField(max_length=30)),
                ('cli_email2', models.EmailField(blank=True, max_length=30, null=True)),
                ('cli_telefone1', models.CharField(max_length=14)),
                ('cli_telefone2', models.CharField(blank=True, max_length=14, null=True)),
                ('cli_enderereco', models.CharField(max_length=50)),
                ('cli_complementoenderereco', models.CharField(max_length=50)),
                ('cli_cep', models.CharField(max_length=10)),
                ('cli_bairro', models.CharField(max_length=50)),
                ('cli_cidade', models.CharField(max_length=20)),
                ('cli_estado', models.CharField(max_length=20)),
                ('cli_taxacompra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cli_multa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cli_juros', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cli_taxarecompra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cli_valortotaloperacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cli_datacadastro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Dfactoring',
            fields=[
                ('fac_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('fac_razaosocial', models.CharField(max_length=50)),
                ('fac_nomefantasia', models.CharField(max_length=50)),
                ('fac_cnpj', models.CharField(max_length=20)),
                ('fac_im', models.CharField(max_length=20)),
                ('fac_ie', models.CharField(max_length=20)),
                ('fac_email1', models.EmailField(max_length=30)),
                ('fac_email2', models.EmailField(blank=True, max_length=30, null=True)),
                ('fac_telefone1', models.CharField(max_length=14)),
                ('fac_telefone2', models.CharField(blank=True, max_length=14, null=True)),
                ('fac_enderereco', models.CharField(max_length=50)),
                ('fac_complementoenderereco', models.CharField(max_length=50)),
                ('fac_cep', models.CharField(max_length=10)),
                ('fac_bairro', models.CharField(max_length=50)),
                ('fac_cidade', models.CharField(max_length=20)),
                ('fac_estado', models.CharField(max_length=20)),
                ('fac_taxacompra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fac_iof', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fac_iofadicional', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fac_pis', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fac_cofins', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fac_float', models.IntegerField()),
                ('fac_multa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fac_juros', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fac_taxarecompra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fac_valortotaloperacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fac_datacadastro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Dpessoas',
            fields=[
                ('pes_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('pes_nome', models.CharField(max_length=50)),
                ('pes_cpf', models.CharField(max_length=14)),
                ('pes_rg', models.CharField(max_length=14)),
                ('pes_estadocivil', models.CharField(max_length=14)),
                ('pes_nacionalidade', models.CharField(max_length=20)),
                ('pes_email1', models.EmailField(max_length=30)),
                ('pes_email2', models.EmailField(blank=True, max_length=30, null=True)),
                ('pes_telefone1', models.CharField(max_length=14)),
                ('pes_telefone2', models.CharField(blank=True, max_length=14, null=True)),
                ('pes_profissao', models.CharField(max_length=30)),
                ('pes_enderereco', models.CharField(max_length=50)),
                ('pes_complementoenderereco', models.CharField(max_length=50)),
                ('pes_cep', models.CharField(max_length=10)),
                ('pes_bairro', models.CharField(max_length=50)),
                ('pes_cidade', models.CharField(max_length=20)),
                ('pes_estado', models.CharField(max_length=20)),
                ('pes_tipopessoa', models.CharField(max_length=6)),
                ('pes_datacadastro', models.DateField()),
                ('cli_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.dcliente')),
                ('fac_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.dfactoring')),
            ],
        ),
        migrations.CreateModel(
            name='Dcontratomae',
            fields=[
                ('cma_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('cma_validadecontrato', models.DateField()),
                ('cma_datacadastro', models.DateField()),
                ('cli_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.dcliente')),
                ('fac_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.dfactoring')),
            ],
        ),
    ]
