# Generated by Django 4.2.7 on 2024-01-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcliente',
            name='cli_telefone1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='dcliente',
            name='cli_telefone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='dfactoring',
            name='fac_ie',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dfactoring',
            name='fac_telefone1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='dfactoring',
            name='fac_telefone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_telefone1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_telefone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_telefone3',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_telefone4',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_telefone5',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_telefone6',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='dpessoas',
            name='pes_telefone1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='dpessoas',
            name='pes_telefone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
