# Generated by Django 4.2.7 on 2024-01-02 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dcarteira',
            old_name='car_valortotal',
            new_name='car_saldo',
        ),
    ]
