# Generated by Django 4.2.7 on 2023-12-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_dpessoas_pes_tipopessoa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doperacao',
            name='ope_bairro1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_bairro2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_bairro3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_bairro4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_bairro5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_bairro6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_cep1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_cep2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_cep3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_cep4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_cep5',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_cep6',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_cidade1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_cidade2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_cidade3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_cidade4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_cidade5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_cidade6',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_cnpj1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_cnpj2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_cnpj3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_cnpj4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_cnpj5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_cnpj6',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_complementoendereco1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_complementoendereco2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_complementoendereco3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_complementoendereco4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_complementoendereco5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_complementoendereco6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_email1',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_email2',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_email3',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_email4',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_email5',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_email6',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_endereco1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_endereco2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_endereco3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_endereco4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_endereco5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_endereco6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_estado1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_estado2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_estado3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_estado4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_estado5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_estado6',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_nomecontato1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_nomecontato2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_nomecontato3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_nomecontato4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_nomecontato5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_nomecontato6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_numtitulo1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_numtitulo2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_numtitulo3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_numtitulo4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_numtitulo5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_numtitulo6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_prazo2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_prazo3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_prazo4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_prazo5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_prazo6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_razaosocial1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_razaosocial2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_razaosocial3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_razaosocial4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_razaosocial5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_razaosocial6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_taxadecompraefetiva2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_taxadecompraefetiva3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_taxadecompraefetiva4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_taxadecompraefetiva5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_taxadecompraefetiva6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_taxaperiodo2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_taxaperiodo3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_taxaperiodo4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_taxaperiodo5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_taxaperiodo6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_telefone1',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_telefone2',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_telefone3',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_telefone4',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_telefone5',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_telefone6',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_valorcompra2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_valorcompra3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_valorcompra4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_valorcompra5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_valorcompra6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_valoriof2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_valoriof3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_valoriof4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_valoriof5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_valoriof6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_valoriofadicional2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_valoriofadicional3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_valoriofadicional4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_valoriofadicional5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_valoriofadicional6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_valorliquido2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_valorliquido3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_valorliquido4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_valorliquido5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_valorliquido6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_valortotal2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_valortotal3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_valortotal4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_valortotal5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_valortotal6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_vencimento2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_vencimento3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_vencimento4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_vencimento5',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_vencimento6',
            field=models.DateField(blank=True, null=True),
        ),
    ]
