# Generated by Django 4.2.7 on 2023-12-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_dsimulacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dsimulacao',
            old_name='sim_prazo',
            new_name='sim_prazo1',
        ),
        migrations.RenameField(
            model_name='dsimulacao',
            old_name='sim_taxadecompraefetiva',
            new_name='sim_taxadecompraefetiva1',
        ),
        migrations.RenameField(
            model_name='dsimulacao',
            old_name='sim_taxaperiodo',
            new_name='sim_taxaperiodo1',
        ),
        migrations.RenameField(
            model_name='dsimulacao',
            old_name='sim_valorcompra',
            new_name='sim_valorcompra1',
        ),
        migrations.RenameField(
            model_name='dsimulacao',
            old_name='sim_valoriof',
            new_name='sim_valoriof1',
        ),
        migrations.RenameField(
            model_name='dsimulacao',
            old_name='sim_valoriofadicional',
            new_name='sim_valoriofadicional1',
        ),
        migrations.RenameField(
            model_name='dsimulacao',
            old_name='sim_valorliquido',
            new_name='sim_valorliquido1',
        ),
        migrations.RenameField(
            model_name='dsimulacao',
            old_name='sim_valortotal',
            new_name='sim_valortotal1',
        ),
        migrations.RenameField(
            model_name='dsimulacao',
            old_name='sim_vencimento',
            new_name='sim_vencimento1',
        ),
    ]
