# Generated by Django 4.2.7 on 2024-02-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_dcarteira_car_titulonumero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcliente',
            name='cli_valortotaloperacao',
            field=models.DecimalField(decimal_places=2, max_digits=17),
        ),
        migrations.AlterField(
            model_name='doperacao',
            name='ope_status',
            field=models.CharField(choices=[('2', 'OPERAÇÃO'), ('3', 'CANCELADO'), ('4', 'FINALIZADO')], max_length=1),
        ),
    ]
