# Generated by Django 4.2.7 on 2023-12-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_rename_sim_prazo_dsimulacao_sim_prazo1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsimulacao',
            name='sim_status',
            field=models.CharField(choices=[('1', 'SIMULAÇÃO'), ('2', 'OPERAÇÃO')], max_length=1),
        ),
    ]
