# Generated by Django 4.2.7 on 2024-03-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_dcliente_cli_juros_alter_dcliente_cli_multa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcliente',
            name='cli_datafundacao',
            field=models.DateField(default='2023-06-06'),
        ),
        migrations.AddField(
            model_name='dfactoring',
            name='fac_datafundacao',
            field=models.DateField(default='2023-06-06'),
        ),
        migrations.AddField(
            model_name='doperacao',
            name='ope_recompra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dpessoas',
            name='pes_datanascimento',
            field=models.DateField(default='2023-06-06'),
        ),
        migrations.AddField(
            model_name='dsimulacao',
            name='sim_recompra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
