# Generated by Django 4.2.7 on 2023-12-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_doperacao_sim_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doperacao',
            name='sim_id',
        ),
    ]
