# Generated by Django 4.2.7 on 2024-01-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_dcliente_cli_complementoendereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doperacao',
            name='ope_id',
            field=models.AutoField(default=190, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dsimulacao',
            name='sim_id',
            field=models.AutoField(default=190, editable=False, primary_key=True, serialize=False),
        ),
    ]
