# Generated by Django 4.2.7 on 2024-01-24 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_alter_doperacao_ope_id_alter_dsimulacao_sim_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doperacao',
            old_name='ope_myfloat',
            new_name='ope_float',
        ),
        migrations.RenameField(
            model_name='doperacao',
            old_name='ope_taxadecompra',
            new_name='ope_taxacompra',
        ),
        migrations.RenameField(
            model_name='dsimulacao',
            old_name='sim_myfloat',
            new_name='sim_float',
        ),
        migrations.RenameField(
            model_name='dsimulacao',
            old_name='sim_taxadecompra',
            new_name='sim_taxacompra',
        ),
    ]
