# Generated by Django 4.2.7 on 2023-12-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_remove_doperacao_sim_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doperacao',
            name='ope_taxadecompra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
