# Generated by Django 4.2.7 on 2024-01-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_rename_ope_myfloat_doperacao_ope_float_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcliente',
            name='cli_taxacompra',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
    ]
