# Generated by Django 4.2.7 on 2024-01-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_alter_dcliente_cli_taxacompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcliente',
            name='cli_juros',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
        migrations.AlterField(
            model_name='dcliente',
            name='cli_multa',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
        migrations.AlterField(
            model_name='dcliente',
            name='cli_taxarecompra',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dcliente',
            name='cli_valortotaloperacao',
            field=models.DecimalField(decimal_places=7, max_digits=17),
        ),
        migrations.AlterField(
            model_name='dsimulacao',
            name='sim_acrescimos',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dsimulacao',
            name='sim_despesas',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dsimulacao',
            name='sim_taxacompra',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
