# Generated by Django 4.2.7 on 2024-01-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_alter_dcliente_cli_juros_alter_dcliente_cli_multa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsimulacao',
            name='sim_valortotal1',
            field=models.DecimalField(decimal_places=7, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dsimulacao',
            name='sim_valortotal2',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='dsimulacao',
            name='sim_valortotal3',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='dsimulacao',
            name='sim_valortotal4',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='dsimulacao',
            name='sim_valortotal5',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='dsimulacao',
            name='sim_valortotal6',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
    ]
